version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.9
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-
      - run:
          name: Installing Dependencies
          command: |
            yarn install
            sudo apt-get install postgresql-client
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run:
          name: Wait for Postgres to start
          command: dockerize -wait tcp://packy.db.elephantsql.com:5432 -timeout 1m
      - run:
          name: Run Tests
          command: |
            yarn test
